name: Automated retrieval
run-name: Automated retrieval
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
permissions:
  contents: write

jobs:
  # This condition lets the job run even if any of the previous jobs failed
  # ${{ ! cancelled() }}

  # This condition prevents the job from running if the test job failed
  # ${{ needs.test-functions.result == 'success' }}

  test-functions:
    uses: ./.github/workflows/test_functions.yml

  build-nsfw:
    needs: test-functions
    uses: ./.github/workflows/build_nsfw.yml

  validate-files:
    needs: [test-functions, build-nsfw]
    if: ${{ ! cancelled() && needs.test-functions.result == 'success' }}
    uses: ./.github/workflows/validate_files.yml
    secrets: inherit

  retrieve-domains:
    needs: [test-functions, validate-files]
    if: ${{ ! cancelled() && needs.test-functions.result == 'success' }}
    uses: ./.github/workflows/retrieve_domains.yml
    secrets: inherit

  build:
    needs: [test-functions, retrieve-domains]
    if: ${{ ! cancelled() && needs.test-functions.result == 'success' }}
    uses: ./.github/workflows/build_lists.yml

  update-readme:
    needs: build
    # Run only if build was successful
    if: ${{ ! cancelled() && needs.build.result == 'success' }}
    uses: ./.github/workflows/update_readme.yml
