name: Process issue
on:
  issues:
    types:
      - labeled
permissions:
  contents: write
  issues: write

jobs:
  add-to-blocklist:
    if: ${{ github.event.label.name == 'add domains' && github.actor == github.repository_owner }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Process domains
        run: |
          readonly DOMAIN_REGEX='(?:([\p{L}\p{N}][\p{L}\p{N}-]*[\p{L}\p{N}]|[\p{L}\p{N}])\.)+[\p{L}}][\p{L}\p{N}-]*[\p{L}\p{N}]'

          # Get domains from issue, add to pending file, and print in
          # closing comment.
          gh issue close ${{ github.event.issue.number }} -c \
          "Sent the following domains for processing:
          \`\`\`
          $(
            mawk '
              /###/ {
                  i++
              }
              i == 1 && !/###/ {
                  print
              }
              i == 2 {
                  exit
              }' <<< "${{ github.event.issue.body }}" \
              | grep -Po "^(https?://)?\K${DOMAIN_REGEX}" \
              | xargs -I {} sh -c 'printf {}; printf {} >> data/pending/Manual.tmp'
            )
          \`\`\`"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Push
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
          git add .
          git diff-index --quiet HEAD || git commit -m "CI: process domains from #${{ github.event.issue.number }}"
          git push -q

  add-to-whitelist:
    if: ${{ github.event.label.name == 'whitelist domains' && github.actor == github.repository_owner }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Process domains
        run: |
          readonly DOMAIN_REGEX='(?:([\p{L}\p{N}][\p{L}\p{N}-]*[\p{L}\p{N}]|[\p{L}\p{N}])\.)+[\p{L}}][\p{L}\p{N}-]*[\p{L}\p{N}]'

          # Get domains from issue, add to whitelist, remove from blacklist,
          # and print in closing comment.
          gh issue close ${{ github.event.issue.number }} -c \
          "Sent the following domains to be whitelisted:
          \`\`\`
          $(
            mawk '
              /###/ {
                  i++
              }
              i == 1 && !/###/ {
                  print
              }
              i == 2 {
                  exit
              }' <<< "${{ github.event.issue.body }}" \
              | grep -Po "^(https?://)?\K${DOMAIN_REGEX}" \
              | tee >(mawk '{ gsub(/\./, "\."); print "^" $0 "$" }' \
              | sort -u - config/whitelist.txt -o config/whitelist.txt) \
              | xargs -I {} sh -c 'printf {}; sed -i '/{}$/d' config/blacklist.txt'
            )
          \`\`\`"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Push
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
          git add .
          git diff-index --quiet HEAD || git commit -m "CI: whitelist domains from #${{ github.event.issue.number }}"
          git push -q

  build:
    needs: add-to-blocklist
    if: ${{ github.event.label.name == 'add domains' && github.actor == github.repository_owner }}
    uses: ./.github/workflows/retrieve_domains.yml
    secrets: inherit

  whitelist:
    needs: add-to-whitelist
    if: ${{ github.event.label.name == 'whitelist domains' && github.actor == github.repository_owner }}
    uses: ./.github/workflows/validate_domains.yml
    secrets: inherit
