name: Retrieve domains and validate
on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  retrieve:
    uses: ./.github/workflows/retrieve_domains.yml
    secrets: inherit

  validate:
    needs: retrieve
    uses: ./.github/workflows/validate_files.yml
    secrets: inherit
